### ISSUE TITLE
Colored Amiga Font Rendering

### ISSUE THREAD

**Issue by sjs** [ansilove/ansilove.js#5]
When rendering with any of the amiga fonts, if the text uses ANSI colors, the fonts render strangely (as if they are bold, maybe?).  Screenshot below. See the center of the # character for the most obvious example.

![Screenshot](http://i.imgur.com/0zD4u8Y.png)

This issue was first noticed by Haliphax in #ascii. The example file is break_06.zip/jpclvn1.ans.

**Comment by haliphax** [comment]
An extra pixel also seems to be sneaking its way into the corner of the glyphs for `/` and `\`.

Note: This is not just for "ANSI colors", but for the "high" ANSI colors (8-15). 0-7 render fine, it seems.

**Comment by fcambus** [comment]
Possibly relevant for the bold issue : https://github.com/ansilove/ansilove/commit/42ddac49e4b2068cd596adeed575a5fac36cbb72

**Comment by andyherbert** [comment]
I'll submit a fix for this at the weekend. 

I originally copied the behaviour of ansilove/php, which at the time gave the same result as shown here, but sometime later @fcambus submitted a fix to only display bold text when in CED or Workbench mode (and I neglected to copy the same logic here).
The bug @haliphax has discovered is a separate issue, but I have a sneaking suspicion that this can be fixed with a simple bounds check when generating the font from the bit mask (again, I'll fix this at the weekend).

**Comment by andyherbert** [comment]
@haliphax The stray pixel issue should also be fixed now.

**Comment by haliphax** [comment]
Awesome. Thanks, bud!
